### PR TITLE
Fixes sizing for EXIF-rotated images

### PR DESCRIPTION
**Pull request by start141**
Please see #699.

### CODE REVIEW

**Comment by start141** [comment]
Why build  failed? @JakeWharton

**Comment by ChristianBecker** [comment]
You could check the Travis build failure yourself at: https://travis-ci.org/square/picasso/jobs/64366824

```
[INFO] --- maven-checkstyle-plugin:2.10:checkstyle (default) @ picasso ---
[INFO] Starting audit...
/home/travis/build/square/picasso/picasso/src/main/java/com/squareup/picasso/BitmapHunter.java:121: Line is longer than 100 characters (found 104).
/home/travis/build/square/picasso/picasso/src/main/java/com/squareup/picasso/BitmapHunter.java:511: Line has trailing spaces.
Audit done.
```

**Comment by start141** [comment]
@ChristianBecker Yeah, I know. but it look like not my wrong.
The message you finded is Log [INFO], it would make build failure?

**Comment by ChristianBecker** [comment]
Yeah, those are the reasons for the build failure
```
[ERROR] Failed to execute goal org.apache.maven.plugins:maven-checkstyle-plugin:2.10:checkstyle (default) on project picasso: An error has occurred in Checkstyle report generation. Failed during checkstyle execution: There are 2 checkstyle errors. -> [Help 1]
```

**Comment by start141** [comment]
@ChristianBecker Thank you! I try to fix it.

**Comment by start141** [comment]
@ChristianBecker How to retry build?

**Comment by ChristianBecker** [comment]
I have no idea, sorry. You could squash all your commits to a single one ( using http://rebaseandsqua.sh/ ) and force push the result. That should trigger a new build.

**Comment by start141** [comment]
Thank you very much!

**Pull request closed without merging**
