### PR TITLE
Disable BuildConfig generation.

### PR DESCRIPTION
**Pull request by NightlyNexus**

### CODE REVIEW

**Comment by NightlyNexus** [comment]
failed, hm? works locally for me at least after also applying #1743. have no idea what's wrong in Robolectric...

**Comment by NightlyNexus** [comment]
okay, errors make sense now. just missing the BuildConfig that Robolectric wants.

**Comment by JakeWharton** [comment]
Rebase? Does it still fail?

**Comment by NightlyNexus** [comment]
tests still fail for me locally after rebasing.
`java.lang.RuntimeException: Could not load class: com.squareup.picasso.BuildConfig`

**Comment by vanniktech** [comment]
Afaik, robolectric will try load it.

**Comment by JakeWharton** [comment]
There's a lever we can pull somewhere to get it to stop.

**Comment by jrodbx** [comment]
IIRC, this requires bumping to a later version of Robolectric which will introduce other issues (see https://github.com/robolectric/robolectric/issues/3242 for an example).  IMO, it's not worth the effort at the moment.

**Pull request closed without merging**
