### PR TITLE
Disallow creating instances of PicassoProvider.

### PR DESCRIPTION
**Pull request by NightlyNexus**

### CODE REVIEW

**Comment by JakeWharton** [comment]
There is an error prone check for this. Let's turn it on.

**Comment by NightlyNexus** [comment]
I can't a check for this. The closest I could find is http://errorprone.info/bugpattern/PrivateConstructorForNoninstantiableModule

I haven't followed EP in a while, so I could have missed it.

**Comment by NightlyNexus** [comment]
Ah, dunno how I missed that. I tried this locally, and it got upset about BuildConfig.java. We can do this when we stop generating that thing.

**Comment by JakeWharton** [comment]
You can also exclude generated stuff:
https://android.googlesource.com/platform/frameworks/support/+/androidx-master-dev/buildSrc/src/main/kotlin/androidx/build/ErrorProneConfiguration.kt#72

**Pull request merged**
