### PR TITLE
Remove synthetic accessors.

### PR DESCRIPTION
**Pull request by NightlyNexus**
Ran the IJ inspection over the project.
Fwiw, I just don't use `private` in Java.

### CODE REVIEW

**Comment by NightlyNexus** [comment]
https://issuetracker.google.com/issues/37075533

**Comment by JakeWharton** [comment]
And if my math calculations are correct, 11 comes directly after 10!

**Comment by jrodbx** [comment]
Uh, I don't think we should weaken access for the sake of synthetic accessors.  Wouldn't they get stripped away anyway at build time?

**Comment by JakeWharton** [comment]
Nope!

**Comment by jrodbx** [comment]
Ah ok.  Also, read the issue that @NightlyNexus linked.  Makes sense!

**Comment by NightlyNexus** [comment]
Evil plan disclosure:
My zealotry against private is actually for readability more than avoiding synthetic methods. Synthetic methods are merely an excuse to spread my mischief.

Code in a feature package or library knows its intention. Private is a noisy modifier that hasn't helped me in practice, past first learning Java. (I wish Kotlin defaulted to internal.)

A religious discussion for a very different thread, though, haha.

**Pull request merged**
