### PR TITLE
Add support for OkHttp 3.

### PR DESCRIPTION
**Pull request by JakeWharton**
@swankjesse

### CODE REVIEW

**Comment by swankjesse** [comment]
Sweet!

**Comment by niteshreddy** [comment]
@JakeWharton @swankjesse any update on when this issue will be released?

**Comment by martinbonnin** [comment]
+1 for a release, I'm using 2.5.2 which looks like it doesn't have okhttp3 support.

**Comment by JakeWharton** [comment]
Use 2.6.0-SNAPSHOT

**Pull request merged**
