### PR TITLE
Clear the reference to the placeholder when not needed anymore

### LINKED ISSUE #968: PicassoDrawable's placeholder is not released if the drawable becomes another PicassoDrawable's placeholder.
I have an ImageView that loops through remote images like a "slideshow".

Because I still want to display the last image while it's loading from the server, I do `setPlaceholder(target.getDrawable())` which sets the previous PicassoDrawable as the placeholder of the new PicassoDrawable.

This leaks memory over time because the every PicassoDrawable is holding a reference to the previous PicassoDrawable through `placeholder` member variable.

### PR DESCRIPTION
**Pull request by GuillaumeDelente**
Should fix #968

### CODE REVIEW

**Comment by JakeWharton** [comment]
Thanks.

**Comment by JakeWharton** [comment]
The placeholder image is set to `null` when the animation completes and if you are not animating then the placeholder field is never set. So I'm not sure this actually fixes anything.

**Comment by JakeWharton** [comment]
I'm reverting this and re-opening the original issue because I'm not confident this fixes any problem.

**Comment by GuillaumeDelente** [comment]
I remember the placeholder being set even if not animating but need to confirm.

**Comment by JakeWharton** [comment]
The constructor contains this code:
```java
     boolean fade = loadedFrom != MEMORY && !noFade;
     if (fade) {
       this.placeholder = placeholder;
       animating = true;
       startTimeMillis = SystemClock.uptimeMillis();
```
but I'd definitely be interested in figuring out what's going on here.

**Pull request merged**
