### PR TITLE
Generalized dimension recalculation on rotation fixes

### LINKED ISSUE #689: Fit horizontally and crop vertically
How can I make a photo fit horizontally in a dyncamically created ImageView and crop it vertically?

The same question with a sample of my code has been posted on StackOverflow: http://stackoverflow.com/questions/26208266/set-maximum-width-to-load-images-with-picasso/26208302?noredirect=1#comment41099837_26208302

### LINKED ISSUE #691: Rotate if necessary
How can I rotate the picture automatically if the photo has been taken in a different orientation?

### LINKED ISSUE #875: centerCrop + exif rotation = incorrect cropping
Summary
---
If you load an image from a file where the data is is rotated with the center crop option it is incorrectly displayed.

It would appear as if the cropping is done before the rotation is applied.

Code
---
```java
Picasso.with(this)
    .load(file)
    .fit()
    .centerCrop()
    .into(imageView);
```

Image
---
Landscape_6

Result
---
The pink stuff is the image view.

Result

### PR DESCRIPTION
**Pull request by JohnWowUs**
A general fix for the issues referred to in PR:

closes #699 
closes #875 
closes #689
closes #691

### CODE REVIEW

**Comment by start141** [comment]
Hi, @dnkoutso @JohnWowUs .

I think you should add
```
+    if (exifRotation == 90 || exifRotation == 270) {
+      int tmpHeight = height;
+      height = width;
+      width = tmpHeight;
+    }
```
in `calculateInSampleSize`, to set the right `sampleSize`,

and edit
```
float sx =
            targetWidth != 0 ? targetWidth / (float) inWidth : targetHeight / (float) inHeight;
float sy =
            targetHeight != 0 ? targetHeight / (float) inHeight : targetWidth / (float) inWidth;
         if (shouldResize(onlyScaleDown, inWidth, inHeight, targetWidth, targetHeight)) {
-          matrix.preScale(sx, sy);
+          if (exifRotation == 90 || exifRotation == 270) {
+            matrix.preScale(sy, sx);
+          } else {
+            matrix.preScale(sx, sy);
+          }
         }
```
in `transformResult`, to set the right `sx`  and `sy`  of `matrix` .

The code Just a reference.#1040
Thanks!

**Comment by JohnWowUs** [comment]
I think you're right about the problem in calculateInSampleSize. 

The transformresult bit is right as we do the width/height swap in the exif part of the method. 
I have, however, discovered another problem in the calculation (we should be recalculating inWidth and inHeight rather than the requested targetWidth and targetHeight). 

You should raise an issue for the calculateInSampleSize problem.

**Comment by start141** [comment]
Sorry! What about your mean calculation in 'discovered another problem in the calculation'?

**Comment by start141** [comment]
@JohnWowUs 
I added an isssue about the calculateInSampleSize problem. #1050

**Pull request merged**
