### PR TITLE
Add TextDrawable

### PR DESCRIPTION
**Pull request by jordan1997**
The pull request implements use text as placeholder or error holder.
Implemented following functions:
1. Text color;
2. Text size;
3. Text font;
4. Background color;
5. Text gravity;
6. Text padding.

### CODE REVIEW

**Comment by JakeWharton** [comment]
We do not want to be responsible for maintaining such complexity, and I don't see any reason to tie such functionality to this project since it can be used anywhere a Drawable can be used.

**Comment by jordan1997** [comment]
@JakeWharton I will support with functionality in the future. 
About reason, developers will use this each time, when app shows provide with the avatar. (More apps show two letters in the image view when user doesn't have avatar).

**Comment by jordan1997** [comment]
I fixed check style. @JakeWharton Can you reopen pull reqest? I want to update it.

**Comment by JakeWharton** [comment]
We do not want to add this functionality to Picasso. If you'd like, you can
publish it as a standalone library for use with Picasso and anywhere else.

**Comment by jordan1997** [comment]
Ok :(

**Pull request closed without merging**
