### PR TITLE
Stop placeholder animation on errors

### PR DESCRIPTION
**Pull request by jobi**

### CODE REVIEW

**Comment by JakeWharton** [comment]
Are you able to write a test for this? Look at the test which verifies we call `start()` for ideas, perhaps.

**Comment by jobi** [comment]
Added a test. By the way I couldn't find the test that checks that start() is called?

**Comment by JakeWharton** [comment]
Oh maybe I lied! Will look later.

**Comment by JakeWharton** [comment]
Thanks!

**Pull request merged**
